//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWebFormsClient.ProductReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TProduct", Namespace="http://schemas.datacontract.org/2004/07/ShopService.Transporter")]
    [System.SerializableAttribute()]
    public partial class TProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int categoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int timestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int category {
            get {
                return this.categoryField;
            }
            set {
                if ((this.categoryField.Equals(value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                if ((this.stockField.Equals(value) != true)) {
                    this.stockField = value;
                    this.RaisePropertyChanged("stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int timestamp {
            get {
                return this.timestampField;
            }
            set {
                if ((this.timestampField.Equals(value) != true)) {
                    this.timestampField = value;
                    this.RaisePropertyChanged("timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductReference.IProduct")]
    public interface IProduct {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Create", ReplyAction="http://tempuri.org/IProduct/CreateResponse")]
        bool Create(ShopWebFormsClient.ProductReference.TProduct product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Create", ReplyAction="http://tempuri.org/IProduct/CreateResponse")]
        System.Threading.Tasks.Task<bool> CreateAsync(ShopWebFormsClient.ProductReference.TProduct product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Read", ReplyAction="http://tempuri.org/IProduct/ReadResponse")]
        ShopWebFormsClient.ProductReference.TProduct Read(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Read", ReplyAction="http://tempuri.org/IProduct/ReadResponse")]
        System.Threading.Tasks.Task<ShopWebFormsClient.ProductReference.TProduct> ReadAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/ReadAll", ReplyAction="http://tempuri.org/IProduct/ReadAllResponse")]
        ShopWebFormsClient.ProductReference.TProduct[] ReadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/ReadAll", ReplyAction="http://tempuri.org/IProduct/ReadAllResponse")]
        System.Threading.Tasks.Task<ShopWebFormsClient.ProductReference.TProduct[]> ReadAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Update", ReplyAction="http://tempuri.org/IProduct/UpdateResponse")]
        bool Update(ShopWebFormsClient.ProductReference.TProduct product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Update", ReplyAction="http://tempuri.org/IProduct/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(ShopWebFormsClient.ProductReference.TProduct product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Delete", ReplyAction="http://tempuri.org/IProduct/DeleteResponse")]
        bool Delete(ShopWebFormsClient.ProductReference.TProduct product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Delete", ReplyAction="http://tempuri.org/IProduct/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(ShopWebFormsClient.ProductReference.TProduct product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Restock", ReplyAction="http://tempuri.org/IProduct/RestockResponse")]
        bool Restock(ShopWebFormsClient.ProductReference.TProduct product, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Restock", ReplyAction="http://tempuri.org/IProduct/RestockResponse")]
        System.Threading.Tasks.Task<bool> RestockAsync(ShopWebFormsClient.ProductReference.TProduct product, int quantity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductChannel : ShopWebFormsClient.ProductReference.IProduct, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductClient : System.ServiceModel.ClientBase<ShopWebFormsClient.ProductReference.IProduct>, ShopWebFormsClient.ProductReference.IProduct {
        
        public ProductClient() {
        }
        
        public ProductClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Create(ShopWebFormsClient.ProductReference.TProduct product) {
            return base.Channel.Create(product);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAsync(ShopWebFormsClient.ProductReference.TProduct product) {
            return base.Channel.CreateAsync(product);
        }
        
        public ShopWebFormsClient.ProductReference.TProduct Read(int id) {
            return base.Channel.Read(id);
        }
        
        public System.Threading.Tasks.Task<ShopWebFormsClient.ProductReference.TProduct> ReadAsync(int id) {
            return base.Channel.ReadAsync(id);
        }
        
        public ShopWebFormsClient.ProductReference.TProduct[] ReadAll() {
            return base.Channel.ReadAll();
        }
        
        public System.Threading.Tasks.Task<ShopWebFormsClient.ProductReference.TProduct[]> ReadAllAsync() {
            return base.Channel.ReadAllAsync();
        }
        
        public bool Update(ShopWebFormsClient.ProductReference.TProduct product) {
            return base.Channel.Update(product);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(ShopWebFormsClient.ProductReference.TProduct product) {
            return base.Channel.UpdateAsync(product);
        }
        
        public bool Delete(ShopWebFormsClient.ProductReference.TProduct product) {
            return base.Channel.Delete(product);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(ShopWebFormsClient.ProductReference.TProduct product) {
            return base.Channel.DeleteAsync(product);
        }
        
        public bool Restock(ShopWebFormsClient.ProductReference.TProduct product, int quantity) {
            return base.Channel.Restock(product, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> RestockAsync(ShopWebFormsClient.ProductReference.TProduct product, int quantity) {
            return base.Channel.RestockAsync(product, quantity);
        }
    }
}
