//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopFormsClient.UserReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserReference.IUser")]
    public interface IUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Login", ReplyAction="http://tempuri.org/IUser/LoginResponse")]
        bool Login(string name, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Login", ReplyAction="http://tempuri.org/IUser/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string name, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/AdminLogin", ReplyAction="http://tempuri.org/IUser/AdminLoginResponse")]
        bool AdminLogin(string name, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/AdminLogin", ReplyAction="http://tempuri.org/IUser/AdminLoginResponse")]
        System.Threading.Tasks.Task<bool> AdminLoginAsync(string name, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Create", ReplyAction="http://tempuri.org/IUser/CreateResponse")]
        bool Create(ShopService.Transporter.TUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Create", ReplyAction="http://tempuri.org/IUser/CreateResponse")]
        System.Threading.Tasks.Task<bool> CreateAsync(ShopService.Transporter.TUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Read", ReplyAction="http://tempuri.org/IUser/ReadResponse")]
        ShopService.Transporter.TUser Read(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Read", ReplyAction="http://tempuri.org/IUser/ReadResponse")]
        System.Threading.Tasks.Task<ShopService.Transporter.TUser> ReadAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/ReadAll", ReplyAction="http://tempuri.org/IUser/ReadAllResponse")]
        ShopService.Transporter.TUser[] ReadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/ReadAll", ReplyAction="http://tempuri.org/IUser/ReadAllResponse")]
        System.Threading.Tasks.Task<ShopService.Transporter.TUser[]> ReadAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Update", ReplyAction="http://tempuri.org/IUser/UpdateResponse")]
        bool Update(ShopService.Transporter.TUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Update", ReplyAction="http://tempuri.org/IUser/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(ShopService.Transporter.TUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Delete", ReplyAction="http://tempuri.org/IUser/DeleteResponse")]
        bool Delete(ShopService.Transporter.TUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Delete", ReplyAction="http://tempuri.org/IUser/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(ShopService.Transporter.TUser user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserChannel : ShopFormsClient.UserReference.IUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserClient : System.ServiceModel.ClientBase<ShopFormsClient.UserReference.IUser>, ShopFormsClient.UserReference.IUser {
        
        public UserClient() {
        }
        
        public UserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string name, string pass) {
            return base.Channel.Login(name, pass);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string name, string pass) {
            return base.Channel.LoginAsync(name, pass);
        }
        
        public bool AdminLogin(string name, string pass) {
            return base.Channel.AdminLogin(name, pass);
        }
        
        public System.Threading.Tasks.Task<bool> AdminLoginAsync(string name, string pass) {
            return base.Channel.AdminLoginAsync(name, pass);
        }
        
        public bool Create(ShopService.Transporter.TUser user) {
            return base.Channel.Create(user);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAsync(ShopService.Transporter.TUser user) {
            return base.Channel.CreateAsync(user);
        }
        
        public ShopService.Transporter.TUser Read(int id) {
            return base.Channel.Read(id);
        }
        
        public System.Threading.Tasks.Task<ShopService.Transporter.TUser> ReadAsync(int id) {
            return base.Channel.ReadAsync(id);
        }
        
        public ShopService.Transporter.TUser[] ReadAll() {
            return base.Channel.ReadAll();
        }
        
        public System.Threading.Tasks.Task<ShopService.Transporter.TUser[]> ReadAllAsync() {
            return base.Channel.ReadAllAsync();
        }
        
        public bool Update(ShopService.Transporter.TUser user) {
            return base.Channel.Update(user);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(ShopService.Transporter.TUser user) {
            return base.Channel.UpdateAsync(user);
        }
        
        public bool Delete(ShopService.Transporter.TUser user) {
            return base.Channel.Delete(user);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(ShopService.Transporter.TUser user) {
            return base.Channel.DeleteAsync(user);
        }
    }
}
